### ISSUE TITLE
OSerror when experiment with cylinder-flow dataset

### ISSUE THREAD

**Issue by liluo2** [martenlienen/finite-element-networks#2]
Hi there! When I was playing around with cylinder-flow dataset, there was an error:
```
Traceback (most recent call last):
  File "/home/liluo/anaconda3/lib/python3.9/multiprocessing/queues.py", line 244, in _feed
  File "/home/liluo/anaconda3/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
  File "/home/liluo/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 359, in reduce_storage
  File "/home/liluo/anaconda3/lib/python3.9/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/liluo/anaconda3/lib/python3.9/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
```
I notice that there are 100 pt files for these train/valid/test folders on cylinder-flow dataset. I'm wondering is the problem caused by reading so many files? I adjust my `num_workers` to 4.

**Comment by martenlienen** [comment]
Hey, yes, it can be an issue. The easiest solution is to increase the limit as described here https://stackoverflow.com/questions/16526783/python-subprocess-too-many-open-files
